apriltag_node:
  ros__parameters:
    image_transport: "raw"
    tag_families: "tag36h11"
    tag_sizes: [0.1]
    max_hamming: 0
    z_up: true
    publish_tf: true

    detector:
      threads: 2
      decimate: 1.0
      blur: 0.0
      refine: true
      refine_edges: true
      decode_sharpening: 0.25

    tag:
      ids: [21]
      frames: ["tag36h11:21"]
      sizes: [0.1]
