slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Frame Parameters
    odom_frame: odom  # โครงสร้างของคุณเริ่มต้นที่ odom
    map_frame: map
    base_frame: base_footprint  # โครงสร้างของคุณมี base_footprint
    scan_topic: /scan_merged  # เปลี่ยนตาม topic ของ Lidar
    
    # Other SLAM parameters
    use_map_saver: true
    mode: mapping
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.05
    map_update_interval: 5.0
    resolution: 0.05
    min_laser_range: 0.1
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 14400.0
    stack_size_to_use: 40000000

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 15.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.1
    map_file_name: "/home/cobot/Ros2_directory/recon_ws/map"
    map_start_pose: [0.0, 0.0, 0.0]
    map_start_at_dock: false
    enable_interactive_mode: true
