twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel
        timeout: 0.5
        priority: 10
      keyboard:
        topic: key_vel
        timeout: 0.5
        priority: 90
      joystick:
        topic: joy_vel
        timeout: 0.5
        priority: 100
    locks:
      pause:
        topic: pause_navigation
        timeout: 0.0
        priority: 100
      e_stop:
        topic: e_stop
        timeout: 0.0
        priority: 255