controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - J_Wheel_RR
      - J_Wheel_LR
      - J_Wheel_RF
      - J_Wheel_LF

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

    gains:
      J_Wheel_RR: {p: 2.2, d: 0.12}
      J_Wheel_LR: {p: 2.2, d: 0.12}
      J_Wheel_RF: {p: 2.2, d: 0.12}
      J_Wheel_LF: {p: 2.2, d: 0.12}