slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping
    map_file_name: recon_map
    resolution: 0.05
    min_laser_range: 0.3
    max_laser_range: 20.0
    use_scan_matching: true
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 10